# Setup
title: wav2r
description: Practice
url: https://wav2r.github.io
avatar: /assets/icon.png
paginate: 5
permalink: pretty
cover_image: /assets/blue.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: wav2r
  card: summary
logo: logo.png
social:
  name: Sujin Park
  links:
    - https://twitter.com/
    - https://github.com/
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Songzi Vong
  url: https://github.com/vszhub/
  email: vszhub@gmail.com
